--- 
title: "A 'How-to' Guide for Estimating Animal Diel Activity Using Hierarchical Models"
author: 
  - name: "Authors"
    email: xxx@gmail.com
    affiliation: to populate upon acceptance 
    correspondence: true
site: bookdown::bookdown_site
output: distill::distill_article
documentclass: book
bibliography:
 - book.bib 
 - packages.bib 
 - articles.bib 
 - grateful-refs.bib
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This document contains how-to tutorials that illustrate the use of hierarchical models for the analysis of activity patterns. It accompanies the manuscript HMsActivity 2024."
pdf_document: 
    number_chapters: yes
    toc: yes
    toc_depth: 4
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
---

# Preface {#preface}

This tutorial accompanies the manuscript @HMsActivity2024 and contains step-by-step examples on how to use trigonometric and cyclic cubic spline hierarchical models (HMs) to analyze activity patterns from time-stamped data. We present case studies based on camera-trap data, but these approaches can be applied to data collected via other static sensors (e.g., acoustic recorders).

We start the tutorial by introducing the concept of site-to-site variability in diel activity patterns. Using simulated data, we explore two components of this variability, variability in frequency of site-use and variability in timing of activity (chapter \@ref(var)). We then introduce trigonometric generalized linear mixed models and cyclic cubic spline hierarchical generalized additive models as approaches to estimate animals' diel activity patterns (chapter \@ref(est)). From chapter \@ref(dataprep) to \@ref(temppart), we use real-case studies to illustrate how to organize the data \@ref(dataprep) and apply these hierarchical model approaches. In particular, we present three applications typical of ecological studies focused on activity patterns. We explore: 

* whether a certain species of interest concentrates its activity at one or two specific times of the day (i.e. unimodal and bimodal patterns), or whether its activity is constant throughout the 24-hour cycle (i.e. cathemeral pattern; chapter \@ref(unibim));
* whether changes in diel activity are driven by seasonal or other biotic and abiotic sources of variation (chapter \@ref(cov)). We present examples using both categorical (section \@ref(cat)) and continuous (section \@ref(cont)) variables;
* whether changes in diel activity are linked to the co-occurrence of another species, providing support for the existence of time-partitioning mechanisms that facilitate species' coexistence (chapter \@ref(temppart)).

The tutorial also includes a description of the difference between conditional and marginal mean activity patterns, how we can obtain both means and how this difference is relevant depending on the ecological questions at hand (chapter \@ref(condvsmarg)). We also provide a chapter focused on Kernel Density Estimators (KDEs), currently the most used approach for the estimate of activity patterns (chapter \@ref(kdes)). We compare the three R-packages currently available to estimate diel activity using KDEs (section \@ref(kdespkg)), illustrate the consequences of non-aggregating the data in independent events when estimating diel activity (section \@ref(kdedataaggr)), and compare estimates of activity based on KDEs and hierarchical models (section \@ref(compkde)).

In the Appendix, we provide several additional resources, including:

1\. a description of the function `sim_activity`, a custom-built function used in chapters \@ref(var) and \@ref(est) and throughout the tutorial to simulate activity patterns under different conditions (section \@ref(simfunction)); 

2\. a formulation of the trigonometric and cyclic cubic hierarchical models based on the Poisson distribution, an alternative to the formulation based on the binomial distribution used throughout the tutorial (section \@ref(poisson)); 

3\. an example of how to apply these models in a Bayesian framework (section \@ref(bay));

4\. a link to the [`Diel.Niche` R package](https://github.com/diel-project/Diel-Niche-Modeling/), a framework recently introduced to robustly characterize animal activity patterns as diel phenotypes (section \@ref(DielNiche)).

All analyses were performed in @R-base and the tutorial was compiled using `bookdown` [@bookdown1; @bookdown2]. The camera-trap data used in the real-case examples were collected at 100 locations sampled between 2016 and 2018 in Northern Minnesota, USA [@Iannarilliea2021] and can be accessed at *link upon acceptance*. Further details on these data can be found in @Iannarilliea2021.

## Requirements

Throughout this tutorial, we use several packages. Users interested in compiling the tutorial from source or in reproducing the analysis on their own machine should install them. The code below provides a list of all the libraries needed, checks if they are already installed in the user's local machine, and installs those packages that are not.

``` {r preface1, eval=FALSE, message = FALSE, warnings = FALSE}
list.of.packages <- c("dplyr", "grid", "gridExtra", "GLMMadaptive", "ggpubr", "mgcv", 
                      "tidyr", "lubridate", "lmtest", "activity", "overlap", "circular", 
                      "nimble", "brms", "forcats", "MESS", "suncalc", "grateful"
                      )
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)>0) install.packages(new.packages)
if(!("Diel.Niche" %in% installed.packages()[,"Package"])){
  # Install package from GitHub via the devtools package.
  devtools::install_github("diel-project/Diel-Niche-Modeling",
                         ref="main", dependencies = TRUE,
                         build_vignettes = FALSE
                         )
} 
```

<!-- for articles.bib: Fabiola Iannarilli and Brian D. Gerber and John Erb and John R. Fieberg 
 for index: 
 - name: "Fabiola Iannarilli"
    email: fabiola.iannarilli@gmail.com
    affiliation: Department of Fisheries, Wildlife and Conservation Biology, St. Paul, Minnesota, USA; Max Planck Institute of Animal Behavior, Konstanz, Germany 
    correspondence: true
  - name: "Brian D. Gerber"
    affiliation:  USGS, Colorado Cooperative Fish and Wildlife Research Unit, Colorado State University, Fort Collins, Colorado, USA
  - name: "John Erb"
    affiliation:  Minnesota Department of Natural Resources, Grand Rapids, Minnesota, USA
  - name: "John R. Fieberg"
    affiliation: Department of Fisheries, Wildlife and Conservation Biology, St. Paul, Minnesota, USA
    -->