<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tutorial 6 Modeling activity patterns with covariates | A ‘How-to’ Guide for Estimating Animal Diel Activity Using Hierarchical Models</title>
  <meta name="description" content="This document contains how-to tutorials that illustrate the use of hierarchical models for the analysis of activity patterns. It accompanies the manuscript HMsActivity 2024." />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Tutorial 6 Modeling activity patterns with covariates | A ‘How-to’ Guide for Estimating Animal Diel Activity Using Hierarchical Models" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This document contains how-to tutorials that illustrate the use of hierarchical models for the analysis of activity patterns. It accompanies the manuscript HMsActivity 2024." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tutorial 6 Modeling activity patterns with covariates | A ‘How-to’ Guide for Estimating Animal Diel Activity Using Hierarchical Models" />
  
  <meta name="twitter:description" content="This document contains how-to tutorials that illustrate the use of hierarchical models for the analysis of activity patterns. It accompanies the manuscript HMsActivity 2024." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="unibim.html"/>
<link rel="next" href="temppart.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#requirements"><i class="fa fa-check"></i><b>1.1</b> Requirements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="var.html"><a href="var.html"><i class="fa fa-check"></i><b>2</b> Variability in activity patterns</a>
<ul>
<li class="chapter" data-level="2.1" data-path="var.html"><a href="var.html#variability-in-frequency-of-site-use"><i class="fa fa-check"></i><b>2.1</b> Variability in frequency of site-use</a></li>
<li class="chapter" data-level="2.2" data-path="var.html"><a href="var.html#variability-in-timing-of-activity"><i class="fa fa-check"></i><b>2.2</b> Variability in timing of activity</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="est.html"><a href="est.html"><i class="fa fa-check"></i><b>3</b> Estimating activity patterns from time-stamped data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="est.html"><a href="est.html#simulating-activity-patterns"><i class="fa fa-check"></i><b>3.1</b> Simulating activity patterns</a></li>
<li class="chapter" data-level="3.2" data-path="est.html"><a href="est.html#data-preparation"><i class="fa fa-check"></i><b>3.2</b> Data preparation</a></li>
<li class="chapter" data-level="3.3" data-path="est.html"><a href="est.html#trigonometric-glmms"><i class="fa fa-check"></i><b>3.3</b> Trigonometric GLMMs</a></li>
<li class="chapter" data-level="3.4" data-path="est.html"><a href="est.html#cyclic-cubic-spline-hgams"><i class="fa fa-check"></i><b>3.4</b> Cyclic cubic spline HGAMs</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="dataprep.html"><a href="dataprep.html"><i class="fa fa-check"></i><b>4</b> Data preparation</a></li>
<li class="chapter" data-level="5" data-path="unibim.html"><a href="unibim.html"><i class="fa fa-check"></i><b>5</b> Evaluating hypotheses regarding the shape of activity curves</a></li>
<li class="chapter" data-level="6" data-path="cov.html"><a href="cov.html"><i class="fa fa-check"></i><b>6</b> Modeling activity patterns with covariates</a>
<ul>
<li class="chapter" data-level="6.1" data-path="cov.html"><a href="cov.html#cat"><i class="fa fa-check"></i><b>6.1</b> Categorical covariates</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="cov.html"><a href="cov.html#trigonometric-glmms-1"><i class="fa fa-check"></i><b>6.1.1</b> Trigonometric GLMMs</a></li>
<li class="chapter" data-level="6.1.2" data-path="cov.html"><a href="cov.html#cyclic-cubic-spline-hgams-1"><i class="fa fa-check"></i><b>6.1.2</b> Cyclic cubic spline HGAMs</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="cov.html"><a href="cov.html#cont"><i class="fa fa-check"></i><b>6.2</b> Continuous covariates</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="temppart.html"><a href="temppart.html"><i class="fa fa-check"></i><b>7</b> Temporal partitioning</a></li>
<li class="chapter" data-level="8" data-path="condvsmarg.html"><a href="condvsmarg.html"><i class="fa fa-check"></i><b>8</b> Conditional and marginal mean activity patterns</a>
<ul>
<li class="chapter" data-level="8.1" data-path="condvsmarg.html"><a href="condvsmarg.html#estimating-conditional-and-marginal-mean-activity-patterns"><i class="fa fa-check"></i><b>8.1</b> Estimating conditional and marginal mean activity patterns</a></li>
<li class="chapter" data-level="8.2" data-path="condvsmarg.html"><a href="condvsmarg.html#the-frequentist-framework"><i class="fa fa-check"></i><b>8.2</b> The frequentist framework</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="kdes.html"><a href="kdes.html"><i class="fa fa-check"></i><b>9</b> Kernel Density Estimators</a>
<ul>
<li class="chapter" data-level="9.1" data-path="kdes.html"><a href="kdes.html#dataprepkdes"><i class="fa fa-check"></i><b>9.1</b> Data preparation for KDEs</a></li>
<li class="chapter" data-level="9.2" data-path="kdes.html"><a href="kdes.html#kdespkg"><i class="fa fa-check"></i><b>9.2</b> Comparison of KDE estimators</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="kdes.html"><a href="kdes.html#using-the-overlap-package"><i class="fa fa-check"></i><b>9.2.1</b> Using the overlap package</a></li>
<li class="chapter" data-level="9.2.2" data-path="kdes.html"><a href="kdes.html#using-the-activity-package"><i class="fa fa-check"></i><b>9.2.2</b> Using the activity package</a></li>
<li class="chapter" data-level="9.2.3" data-path="kdes.html"><a href="kdes.html#using-the-circular-package"><i class="fa fa-check"></i><b>9.2.3</b> Using the circular package</a></li>
<li class="chapter" data-level="9.2.4" data-path="kdes.html"><a href="kdes.html#comparing-the-results-and-plotting"><i class="fa fa-check"></i><b>9.2.4</b> Comparing the results and plotting</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="kdes.html"><a href="kdes.html#kdedataaggr"><i class="fa fa-check"></i><b>9.3</b> Aggregating <em>versus</em> non-aggregating data in KDEs</a></li>
<li class="chapter" data-level="9.4" data-path="kdes.html"><a href="kdes.html#compkde"><i class="fa fa-check"></i><b>9.4</b> KDEs <em>versus</em> hierarchical models approaches</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="app.html"><a href="app.html"><i class="fa fa-check"></i><b>10</b> Appendix</a>
<ul>
<li class="chapter" data-level="10.1" data-path="app.html"><a href="app.html#simfunction"><i class="fa fa-check"></i><b>10.1</b> The <em>sim_activity</em> function</a></li>
<li class="chapter" data-level="10.2" data-path="app.html"><a href="app.html#poisson"><i class="fa fa-check"></i><b>10.2</b> Binomial versus other distributions</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="app.html"><a href="app.html#data-preparation-1"><i class="fa fa-check"></i><b>10.2.1</b> Data preparation</a></li>
<li class="chapter" data-level="10.2.2" data-path="app.html"><a href="app.html#trigonometric-pdf-comparison"><i class="fa fa-check"></i><b>10.2.2</b> Trigonometric PDF comparison</a></li>
<li class="chapter" data-level="10.2.3" data-path="app.html"><a href="app.html#cyclic-cubic-pdf-comparison"><i class="fa fa-check"></i><b>10.2.3</b> Cyclic cubic PDF comparison</a></li>
<li class="chapter" data-level="10.2.4" data-path="app.html"><a href="app.html#not-controlling-for-sampling-effort"><i class="fa fa-check"></i><b>10.2.4</b> Not controlling for sampling effort</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="app.html"><a href="app.html#bay"><i class="fa fa-check"></i><b>10.3</b> Activity patterns in the Bayesian framework</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="app.html"><a href="app.html#data-preparation-2"><i class="fa fa-check"></i><b>10.3.1</b> Data preparation</a></li>
<li class="chapter" data-level="10.3.2" data-path="app.html"><a href="app.html#model-setup-and-fitting"><i class="fa fa-check"></i><b>10.3.2</b> Model setup and fitting</a></li>
<li class="chapter" data-level="10.3.3" data-path="app.html"><a href="app.html#model-assessment"><i class="fa fa-check"></i><b>10.3.3</b> Model assessment</a></li>
<li class="chapter" data-level="10.3.4" data-path="app.html"><a href="app.html#model-predictions"><i class="fa fa-check"></i><b>10.3.4</b> Model predictions</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="app.html"><a href="app.html#DielNiche"><i class="fa fa-check"></i><b>10.4</b> Link to the Diel.Niche package</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="app.html"><a href="app.html#data"><i class="fa fa-check"></i><b>10.4.1</b> Data</a></li>
<li class="chapter" data-level="10.4.2" data-path="app.html"><a href="app.html#model-fitting"><i class="fa fa-check"></i><b>10.4.2</b> Model fitting</a></li>
<li class="chapter" data-level="10.4.3" data-path="app.html"><a href="app.html#model-predictions-1"><i class="fa fa-check"></i><b>10.4.3</b> Model predictions</a></li>
<li class="chapter" data-level="10.4.4" data-path="app.html"><a href="app.html#twilight-daytime-and-nighttime"><i class="fa fa-check"></i><b>10.4.4</b> Twilight, daytime, and nighttime</a></li>
<li class="chapter" data-level="10.4.5" data-path="app.html"><a href="app.html#diel.niche"><i class="fa fa-check"></i><b>10.4.5</b> Diel.Niche</a></li>
<li class="chapter" data-level="10.4.6" data-path="app.html"><a href="app.html#conclusion"><i class="fa fa-check"></i><b>10.4.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="app.html"><a href="app.html#info-session"><i class="fa fa-check"></i><b>10.5</b> Info session</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A ‘How-to’ Guide for Estimating Animal Diel Activity Using Hierarchical Models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="cov" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Tutorial 6</span> Modeling activity patterns with covariates<a href="cov.html#cov" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Many researchers exploring activity patterns from camera-trap data sooner or later run into the challenge of estimating how activity patterns vary in response to some conditions, often related to the environment in which the data have been collected. We address this common set of ecological questions in this Tutorial, focusing first on categorical and then on continuous variables.</p>
<div id="cat" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Categorical covariates<a href="cov.html#cat" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The task of comparing activity patterns among different levels of a categorical variable can be achieved using KDE approaches. However, the process can be particularly cumbersome, especially when comparing more than two levels. It requires splitting the dataset of the independent records depending on the levels of the variable of interest, run a KDE for each group of records, and then comparing the results using an ad-hoc test. Conversely, the same task can be accomplished by fitting a hierarchical model to the whole dataset, as we describe here. In Tutorial <a href="kdes.html#compkde">9.4</a>, we repeat this same analyses using the KDE approach, and compare results to those obtained using the trigonometric and cyclic cubic spline hierarchical models.</p>
<p>Again, we use camera-trap records collected between 2016 and 2018 at 100 locations in Northern Minnesota, USA <span class="citation">(<a href="references.html#ref-Iannarilliea2021">Iannarilli et al. 2021</a>)</span>. This time, we use records of American black bear (<em>Ursus americanus</em>) and explore differences in activity patterns of this species between spring and fall.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="cov.html#cb73-1" tabindex="-1"></a><span class="co"># Load Libraries</span></span>
<span id="cb73-2"><a href="cov.html#cb73-2" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb73-3"><a href="cov.html#cb73-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">129</span>)</span>
<span id="cb73-4"><a href="cov.html#cb73-4" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb73-5"><a href="cov.html#cb73-5" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb73-6"><a href="cov.html#cb73-6" tabindex="-1"></a><span class="fu">library</span>(GLMMadaptive)</span>
<span id="cb73-7"><a href="cov.html#cb73-7" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span>
<span id="cb73-8"><a href="cov.html#cb73-8" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb73-9"><a href="cov.html#cb73-9" tabindex="-1"></a><span class="fu">library</span>(forcats) </span></code></pre></div>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="cov.html#cb74-1" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb74-2"><a href="cov.html#cb74-2" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data_input/species_records.csv&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb74-3"><a href="cov.html#cb74-3" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">&quot;BlackBear&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">droplevels</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb74-4"><a href="cov.html#cb74-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DateTimeOriginal =</span> <span class="fu">ymd_hm</span>(DateTimeOriginal))</span>
<span id="cb74-5"><a href="cov.html#cb74-5" tabindex="-1"></a>cov <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data_input/CameraTrapProject_CT_data_for_analysis_MASTER.csv&quot;</span>, <span class="at">as.is =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb74-6"><a href="cov.html#cb74-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date_setup =</span> <span class="fu">mdy</span>(Date_setup),</span>
<span id="cb74-7"><a href="cov.html#cb74-7" tabindex="-1"></a>         <span class="at">Date_retr =</span> <span class="fu">mdy</span>(Date_retr),</span>
<span id="cb74-8"><a href="cov.html#cb74-8" tabindex="-1"></a>         <span class="at">Problem1_from =</span> <span class="fu">mdy</span>(Problem1_from),</span>
<span id="cb74-9"><a href="cov.html#cb74-9" tabindex="-1"></a>         <span class="at">Problem1_to =</span> <span class="fu">mdy</span>(Problem1_to)</span>
<span id="cb74-10"><a href="cov.html#cb74-10" tabindex="-1"></a>         ) </span>
<span id="cb74-11"><a href="cov.html#cb74-11" tabindex="-1"></a></span>
<span id="cb74-12"><a href="cov.html#cb74-12" tabindex="-1"></a><span class="co"># Extract Season information from Session column</span></span>
<span id="cb74-13"><a href="cov.html#cb74-13" tabindex="-1"></a>dat<span class="sc">$</span>Season <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">substr</span>(dat<span class="sc">$</span>Session, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb74-14"><a href="cov.html#cb74-14" tabindex="-1"></a></span>
<span id="cb74-15"><a href="cov.html#cb74-15" tabindex="-1"></a><span class="co"># Merge time of deployment and retrieval + problems</span></span>
<span id="cb74-16"><a href="cov.html#cb74-16" tabindex="-1"></a>site <span class="ot">&lt;-</span> cov</span>
<span id="cb74-17"><a href="cov.html#cb74-17" tabindex="-1"></a>site<span class="sc">$</span>end <span class="ot">&lt;-</span> <span class="fu">ymd</span>(<span class="st">&quot;2000-01-01&quot;</span>)</span>
<span id="cb74-18"><a href="cov.html#cb74-18" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(site)){</span>
<span id="cb74-19"><a href="cov.html#cb74-19" tabindex="-1"></a>  site<span class="sc">$</span>end[i] <span class="ot">&lt;-</span>  <span class="fu">min</span>(site<span class="sc">$</span>Date_retr[i], </span>
<span id="cb74-20"><a href="cov.html#cb74-20" tabindex="-1"></a>                      site<span class="sc">$</span>Problem1_from[i], </span>
<span id="cb74-21"><a href="cov.html#cb74-21" tabindex="-1"></a>                      <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb74-22"><a href="cov.html#cb74-22" tabindex="-1"></a>                      )</span>
<span id="cb74-23"><a href="cov.html#cb74-23" tabindex="-1"></a>}</span>
<span id="cb74-24"><a href="cov.html#cb74-24" tabindex="-1"></a></span>
<span id="cb74-25"><a href="cov.html#cb74-25" tabindex="-1"></a><span class="co"># Create dataframe to store captures </span></span>
<span id="cb74-26"><a href="cov.html#cb74-26" tabindex="-1"></a>occasions <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">&quot;list&quot;</span>, <span class="at">length =</span> <span class="fu">nrow</span>(site))</span>
<span id="cb74-27"><a href="cov.html#cb74-27" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(site)){</span>
<span id="cb74-28"><a href="cov.html#cb74-28" tabindex="-1"></a>  occasions[[i]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Session =</span> site<span class="sc">$</span>Session[i],</span>
<span id="cb74-29"><a href="cov.html#cb74-29" tabindex="-1"></a>                               <span class="at">Site =</span> site<span class="sc">$</span>Site[i],</span>
<span id="cb74-30"><a href="cov.html#cb74-30" tabindex="-1"></a>                               <span class="at">start =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">ymd_hms</span>(<span class="fu">paste</span>(site<span class="sc">$</span>Date_setup[i], <span class="st">&quot;00:00:00&quot;</span>, <span class="at">sep =</span> <span class="st">&quot; &quot;</span>)), </span>
<span id="cb74-31"><a href="cov.html#cb74-31" tabindex="-1"></a>                                           <span class="at">to =</span> <span class="fu">ymd_hms</span>(<span class="fu">paste</span>(site<span class="sc">$</span>end[i], <span class="st">&quot;23:59:59&quot;</span>, <span class="at">sep =</span> <span class="st">&quot; &quot;</span>)), <span class="at">by =</span> <span class="st">&#39;60 min&#39;</span></span>
<span id="cb74-32"><a href="cov.html#cb74-32" tabindex="-1"></a>                                           )</span>
<span id="cb74-33"><a href="cov.html#cb74-33" tabindex="-1"></a>                               ) <span class="sc">%&gt;%</span> </span>
<span id="cb74-34"><a href="cov.html#cb74-34" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">end =</span> <span class="fu">c</span>(start[<span class="dv">2</span><span class="sc">:</span><span class="fu">length</span>(start)], </span>
<span id="cb74-35"><a href="cov.html#cb74-35" tabindex="-1"></a>                   start[<span class="fu">length</span>(start)]<span class="sc">+</span><span class="fu">minutes</span>(<span class="dv">60</span>)</span>
<span id="cb74-36"><a href="cov.html#cb74-36" tabindex="-1"></a>                   )</span>
<span id="cb74-37"><a href="cov.html#cb74-37" tabindex="-1"></a>           ) </span>
<span id="cb74-38"><a href="cov.html#cb74-38" tabindex="-1"></a>}</span>
<span id="cb74-39"><a href="cov.html#cb74-39" tabindex="-1"></a>occasions <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind.data.frame, occasions)</span>
<span id="cb74-40"><a href="cov.html#cb74-40" tabindex="-1"></a>occasions<span class="sc">$</span>capt <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb74-41"><a href="cov.html#cb74-41" tabindex="-1"></a></span>
<span id="cb74-42"><a href="cov.html#cb74-42" tabindex="-1"></a><span class="co"># Store captures</span></span>
<span id="cb74-43"><a href="cov.html#cb74-43" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(dat)){</span>
<span id="cb74-44"><a href="cov.html#cb74-44" tabindex="-1"></a>  occasions[occasions<span class="sc">$</span>Session <span class="sc">==</span> <span class="fu">as.character</span>(dat<span class="sc">$</span>Session[i]) <span class="sc">&amp;</span> occasions<span class="sc">$</span>Site <span class="sc">==</span> <span class="fu">as.character</span>(dat<span class="sc">$</span>Station[i]) <span class="sc">&amp;</span></span>
<span id="cb74-45"><a href="cov.html#cb74-45" tabindex="-1"></a>              occasions<span class="sc">$</span>start <span class="sc">&lt;=</span> dat<span class="sc">$</span>DateTimeOriginal[i] <span class="sc">&amp;</span> occasions<span class="sc">$</span>end <span class="sc">&gt;</span> dat<span class="sc">$</span>DateTimeOriginal[i], <span class="st">&quot;capt&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb74-46"><a href="cov.html#cb74-46" tabindex="-1"></a>}</span>
<span id="cb74-47"><a href="cov.html#cb74-47" tabindex="-1"></a></span>
<span id="cb74-48"><a href="cov.html#cb74-48" tabindex="-1"></a><span class="co"># Format data </span></span>
<span id="cb74-49"><a href="cov.html#cb74-49" tabindex="-1"></a>occasions<span class="sc">$</span>Time <span class="ot">&lt;-</span> <span class="fu">hour</span>(occasions<span class="sc">$</span>start)</span>
<span id="cb74-50"><a href="cov.html#cb74-50" tabindex="-1"></a>occasions<span class="sc">$</span>Season <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">substr</span>(occasions<span class="sc">$</span>Session, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb74-51"><a href="cov.html#cb74-51" tabindex="-1"></a><span class="fu">table</span>(occasions<span class="sc">$</span>Season, occasions<span class="sc">$</span>capt)</span></code></pre></div>
<pre><code>##    
##          0      1
##   F 222236    244
##   S 347923    773</code></pre>
<p>We obtained 773 (out of 348 696) and 244 (out of 222 480) hourly occasions with at least 1 positive record of a bear in the Spring and Fall sessions, respectively.</p>
<p>We again format the data using a <code>cbind(success, failure)</code> structure as described in Tutorial <a href="dataprep.html#dataprep">4</a>, but this time we also create an additional column (<em>Season</em>) that contains the information about the season (i.e. Spring or Fall) in which the records were collected and use it as an additional grouping criterion.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="cov.html#cb76-1" tabindex="-1"></a>occasions<span class="sc">$</span>Site <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(occasions<span class="sc">$</span>Site)</span>
<span id="cb76-2"><a href="cov.html#cb76-2" tabindex="-1"></a></span>
<span id="cb76-3"><a href="cov.html#cb76-3" tabindex="-1"></a><span class="co"># format data for cbind(success, failure)</span></span>
<span id="cb76-4"><a href="cov.html#cb76-4" tabindex="-1"></a>occasions_cbind <span class="ot">&lt;-</span> occasions <span class="sc">%&gt;%</span> </span>
<span id="cb76-5"><a href="cov.html#cb76-5" tabindex="-1"></a>  <span class="fu">group_by</span>(Site, Time, Season) <span class="sc">%&gt;%</span> </span>
<span id="cb76-6"><a href="cov.html#cb76-6" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">success =</span> <span class="fu">sum</span>(capt),</span>
<span id="cb76-7"><a href="cov.html#cb76-7" tabindex="-1"></a>            <span class="at">failure =</span> <span class="fu">n</span>() <span class="sc">-</span> success)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Site&#39;, &#39;Time&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="cov.html#cb78-1" tabindex="-1"></a><span class="fu">head</span>(occasions_cbind)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
## # Groups:   Site, Time [3]
##   Site   Time Season success failure
##   &lt;fct&gt; &lt;int&gt; &lt;fct&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 10A       0 F            0     100
## 2 10A       0 S            0     159
## 3 10A       1 F            0     100
## 4 10A       1 S            0     159
## 5 10A       2 F            0     100
## 6 10A       2 S            0     159</code></pre>
<p>We save this dataset for applications in other parts of the tutorial.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="cov.html#cb80-1" tabindex="-1"></a><span class="fu">write.csv</span>(occasions_cbind, <span class="at">file =</span> <span class="st">&quot;data_output/occasions_cbind_Ursus_americanus_seasons.csv&quot;</span>)</span></code></pre></div>
<div id="trigonometric-glmms-1" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Trigonometric GLMMs<a href="cov.html#trigonometric-glmms-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Extending the trigonometric hierarchical models to explore the effect of a covariate on activity patterns only requires the inclusion of interactions between the trigonometric terms and the covariate. The interactions allow the coefficients of the trigonometric terms to vary by treatment group, in this case, the two levels of the covariate <em>Season</em>. We start by fitting and visualizing estimated activity curves for the two seasons based on a random intercept-only model in which the random intercept for <em>Site</em> accounts for repeated measures and varying levels of activity at each site:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="cov.html#cb81-1" tabindex="-1"></a><span class="co"># run model</span></span>
<span id="cb81-2"><a href="cov.html#cb81-2" tabindex="-1"></a>trig_rand_int <span class="ot">&lt;-</span> <span class="fu">mixed_model</span>(<span class="at">fixed =</span> <span class="fu">cbind</span>(success, failure) <span class="sc">~</span> </span>
<span id="cb81-3"><a href="cov.html#cb81-3" tabindex="-1"></a>                                              <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb81-4"><a href="cov.html#cb81-4" tabindex="-1"></a>                                              <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb81-5"><a href="cov.html#cb81-5" tabindex="-1"></a>                                              <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb81-6"><a href="cov.html#cb81-6" tabindex="-1"></a>                                              <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> Season,</span>
<span id="cb81-7"><a href="cov.html#cb81-7" tabindex="-1"></a>                             <span class="at">random =</span> <span class="sc">~</span>  <span class="dv">1</span>  <span class="sc">|</span>   Site,</span>
<span id="cb81-8"><a href="cov.html#cb81-8" tabindex="-1"></a>                             <span class="at">data =</span> occasions_cbind, </span>
<span id="cb81-9"><a href="cov.html#cb81-9" tabindex="-1"></a>                             <span class="at">family =</span> <span class="fu">binomial</span>(), </span>
<span id="cb81-10"><a href="cov.html#cb81-10" tabindex="-1"></a>                             <span class="at">iter_EM =</span> <span class="dv">0</span></span>
<span id="cb81-11"><a href="cov.html#cb81-11" tabindex="-1"></a>                             )</span>
<span id="cb81-12"><a href="cov.html#cb81-12" tabindex="-1"></a><span class="fu">summary</span>(trig_rand_int)</span></code></pre></div>
<pre><code>## 
## Call:
## mixed_model(fixed = cbind(success, failure) ~ cos(2 * pi * Time/24) * 
##     Season + sin(2 * pi * Time/24) * Season + sin(2 * pi * Time/12) * 
##     Season + cos(2 * pi * Time/12) * Season, random = ~1 | Site, 
##     data = occasions_cbind, family = binomial(), iter_EM = 0)
## 
## Data Descriptives:
## Number of Observations: 4800
## Number of Groups: 100 
## 
## Model:
##  family: binomial
##  link: logit 
## 
## Fit statistics:
##    log.Lik      AIC      BIC
##  -2284.197 4590.394 4619.051
## 
## Random effects covariance matrix:
##                StdDev
## (Intercept) 0.9022139
## 
## Fixed effects:
##                               Estimate Std.Err  z-value   p-value
## (Intercept)                    -7.3343  0.1216 -60.3133   &lt; 1e-04
## cos(2 * pi * Time/24)           0.4808  0.1102   4.3629   &lt; 1e-04
## SeasonS                         0.7450  0.0869   8.5698   &lt; 1e-04
## sin(2 * pi * Time/24)          -0.5554  0.0989  -5.6164   &lt; 1e-04
## sin(2 * pi * Time/12)          -0.1697  0.0980  -1.7311 0.0834365
## cos(2 * pi * Time/12)          -0.2358  0.0986  -2.3904 0.0168278
## cos(2 * pi * Time/24):SeasonS  -0.7353  0.1275  -5.7657   &lt; 1e-04
## SeasonS:sin(2 * pi * Time/24)   0.3460  0.1100   3.1453 0.0016592
## SeasonS:sin(2 * pi * Time/12)  -0.4507  0.1131  -3.9863   &lt; 1e-04
## SeasonS:cos(2 * pi * Time/12)  -0.3739  0.1135  -3.2945 0.0009859
## 
## Integration:
## method: adaptive Gauss-Hermite quadrature rule
## quadrature points: 11
## 
## Optimization:
## method: quasi-Newton
## converged: TRUE</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="cov.html#cb83-1" tabindex="-1"></a><span class="co"># build estimate of activity</span></span>
<span id="cb83-2"><a href="cov.html#cb83-2" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">with</span>(occasions_cbind, </span>
<span id="cb83-3"><a href="cov.html#cb83-3" tabindex="-1"></a>               <span class="fu">expand.grid</span>(<span class="at">Time =</span> <span class="fu">seq</span>(<span class="fu">min</span>(Time), <span class="dv">24</span>, <span class="at">length.out =</span> <span class="dv">48</span>), </span>
<span id="cb83-4"><a href="cov.html#cb83-4" tabindex="-1"></a>                           <span class="at">Season =</span> <span class="fu">levels</span>(Season)</span>
<span id="cb83-5"><a href="cov.html#cb83-5" tabindex="-1"></a>                           )</span>
<span id="cb83-6"><a href="cov.html#cb83-6" tabindex="-1"></a>               )</span>
<span id="cb83-7"><a href="cov.html#cb83-7" tabindex="-1"></a>pred_rand_int <span class="ot">&lt;-</span> <span class="fu">effectPlotData</span>(trig_rand_int, newdat, <span class="at">marginal =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<div class="sourceCode" id="cb84"><pre class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb84-1"><a href="cov.html#cb84-1" tabindex="-1"></a><span class="co"># plot</span></span>
<span id="cb84-2"><a href="cov.html#cb84-2" tabindex="-1"></a>(pl_trig <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(pred_rand_int, <span class="fu">aes</span>(Time, <span class="fu">plogis</span>(pred))) <span class="sc">+</span></span>
<span id="cb84-3"><a href="cov.html#cb84-3" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> <span class="fu">plogis</span>(low), <span class="at">ymax =</span> <span class="fu">plogis</span>(upp), <span class="at">color =</span> Season, <span class="at">fill =</span> Season), <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb84-4"><a href="cov.html#cb84-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> Season), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb84-5"><a href="cov.html#cb84-5" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;orange&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)) <span class="sc">+</span></span>
<span id="cb84-6"><a href="cov.html#cb84-6" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;orange&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)) <span class="sc">+</span></span>
<span id="cb84-7"><a href="cov.html#cb84-7" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.005</span>)) <span class="sc">+</span></span>
<span id="cb84-8"><a href="cov.html#cb84-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time of Day (Hour)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Predicted Activity Pattern </span><span class="sc">\n</span><span class="st"> (probability)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;A: Hierarchical model, Trigonometric GLMM </span><span class="sc">\n</span><span class="st">(random intercept-only)&quot;</span>)<span class="sc">+</span></span>
<span id="cb84-9"><a href="cov.html#cb84-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb84-10"><a href="cov.html#cb84-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,</span>
<span id="cb84-11"><a href="cov.html#cb84-11" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb84-12"><a href="cov.html#cb84-12" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb84-13"><a href="cov.html#cb84-13" tabindex="-1"></a>        <span class="at">legend.margin=</span><span class="fu">margin</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb84-14"><a href="cov.html#cb84-14" tabindex="-1"></a>        <span class="at">legend.box.margin=</span><span class="fu">margin</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>),</span>
<span id="cb84-15"><a href="cov.html#cb84-15" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb84-16"><a href="cov.html#cb84-16" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb84-17"><a href="cov.html#cb84-17" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb84-18"><a href="cov.html#cb84-18" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">9</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb84-19"><a href="cov.html#cb84-19" tabindex="-1"></a>        <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb84-20"><a href="cov.html#cb84-20" tabindex="-1"></a>        <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb84-21"><a href="cov.html#cb84-21" tabindex="-1"></a>        <span class="at">panel.grid.major.x =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;lightgrey&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;dashed&#39;</span>, <span class="at">linewidth=</span><span class="fl">0.5</span>),</span>
<span id="cb84-22"><a href="cov.html#cb84-22" tabindex="-1"></a>        <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb84-23"><a href="cov.html#cb84-23" tabindex="-1"></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">hjust =</span> <span class="dv">0</span>)</span>
<span id="cb84-24"><a href="cov.html#cb84-24" tabindex="-1"></a>        ) <span class="sc">+</span></span>
<span id="cb84-25"><a href="cov.html#cb84-25" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">23</span>,<span class="at">length.out=</span><span class="dv">7</span>), <span class="at">labels=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">24</span>,<span class="dv">4</span>))</span>
<span id="cb84-26"><a href="cov.html#cb84-26" tabindex="-1"></a>) </span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cat2b"></span>
<img src="HMsActivity_files/figure-html/cat2b-1.png" alt="Predicted probability of activity of black bears in the spring (S) and fall (F) using a random intercept-only trigonometric hierarchical model; shading corresponds to 95% confidence intervals." width="672" />
<p class="caption">
Figure 6.1: Predicted probability of activity of black bears in the spring (S) and fall (F) using a random intercept-only trigonometric hierarchical model; shading corresponds to 95% confidence intervals.
</p>
</div>
<p>The estimated activity patterns show a striking difference between the two seasons. In Spring, black bears had a bimodal activity pattern, with the species active primarily around around 8:00 and 20:00. During the Fall, the species was mostly inactive during the morning.</p>
<p>Importantly, the two seasons were sampled for a different number of days since the study included 3 springs but only 2 falls. This difference in sampling effort makes the direct comparison between the intensity of activity in the two seasons difficult when using KDEs. However, both the trigonometric GLMMs and the cyclic cubic HGAMs (see later) directly account for sampling effort and make this comparison possible. Thus, we can also say that the probability of a black bear being active around 20:00 was overall higher in the Spring than in the Fall.</p>
<p><strong>Model selection:</strong> To test the importance of the seasonal effect on activity patterns of black bears, we can also compare the model above with a model that does not include the covariate using AIC:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="cov.html#cb85-1" tabindex="-1"></a><span class="co"># run model</span></span>
<span id="cb85-2"><a href="cov.html#cb85-2" tabindex="-1"></a>trig_rand_int_no_cov <span class="ot">&lt;-</span> <span class="fu">mixed_model</span>(<span class="at">fixed =</span> <span class="fu">cbind</span>(success, failure) <span class="sc">~</span> </span>
<span id="cb85-3"><a href="cov.html#cb85-3" tabindex="-1"></a>                                              <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">+</span></span>
<span id="cb85-4"><a href="cov.html#cb85-4" tabindex="-1"></a>                                              <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">+</span></span>
<span id="cb85-5"><a href="cov.html#cb85-5" tabindex="-1"></a>                                              <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb85-6"><a href="cov.html#cb85-6" tabindex="-1"></a>                                              <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>),</span>
<span id="cb85-7"><a href="cov.html#cb85-7" tabindex="-1"></a>                                    <span class="at">random =</span> <span class="sc">~</span>  <span class="dv">1</span>  <span class="sc">|</span>   Site,</span>
<span id="cb85-8"><a href="cov.html#cb85-8" tabindex="-1"></a>                                    <span class="at">data =</span> occasions_cbind, </span>
<span id="cb85-9"><a href="cov.html#cb85-9" tabindex="-1"></a>                                    <span class="at">family =</span> <span class="fu">binomial</span>(), </span>
<span id="cb85-10"><a href="cov.html#cb85-10" tabindex="-1"></a>                                    <span class="at">iter_EM =</span> <span class="dv">0</span></span>
<span id="cb85-11"><a href="cov.html#cb85-11" tabindex="-1"></a>                                    )</span>
<span id="cb85-12"><a href="cov.html#cb85-12" tabindex="-1"></a><span class="fu">AIC</span>(trig_rand_int, trig_rand_int_no_cov)</span></code></pre></div>
<pre><code>##                      df      AIC
## trig_rand_int        11 4590.394
## trig_rand_int_no_cov  6 4774.190</code></pre>
<p>The AIC comparison supports the model that includes a seasonal effect on bears’ activity patterns.</p>
<p>We could consider further extending the interaction model by including random slopes.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="cov.html#cb87-1" tabindex="-1"></a>trig_rand_slope <span class="ot">&lt;-</span> <span class="fu">mixed_model</span>(<span class="at">fixed =</span> <span class="fu">cbind</span>(success, failure) <span class="sc">~</span> </span>
<span id="cb87-2"><a href="cov.html#cb87-2" tabindex="-1"></a>                                              <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb87-3"><a href="cov.html#cb87-3" tabindex="-1"></a>                                              <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb87-4"><a href="cov.html#cb87-4" tabindex="-1"></a>                                              <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb87-5"><a href="cov.html#cb87-5" tabindex="-1"></a>                                              <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> Season,</span>
<span id="cb87-6"><a href="cov.html#cb87-6" tabindex="-1"></a>                               <span class="at">random =</span> <span class="sc">~</span>  <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb87-7"><a href="cov.html#cb87-7" tabindex="-1"></a>                                           <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb87-8"><a href="cov.html#cb87-8" tabindex="-1"></a>                                           <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> Season <span class="sc">+</span></span>
<span id="cb87-9"><a href="cov.html#cb87-9" tabindex="-1"></a>                                           <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> Season  <span class="sc">||</span>   Site,</span>
<span id="cb87-10"><a href="cov.html#cb87-10" tabindex="-1"></a>                               <span class="at">data =</span> occasions_cbind, </span>
<span id="cb87-11"><a href="cov.html#cb87-11" tabindex="-1"></a>                               <span class="at">family =</span> <span class="fu">binomial</span>(), </span>
<span id="cb87-12"><a href="cov.html#cb87-12" tabindex="-1"></a>                               <span class="at">iter_EM =</span> <span class="dv">0</span></span>
<span id="cb87-13"><a href="cov.html#cb87-13" tabindex="-1"></a>                               )</span>
<span id="cb87-14"><a href="cov.html#cb87-14" tabindex="-1"></a><span class="fu">summary</span>(trig_rand_slope)</span></code></pre></div>
<p>However, this model is likely to be too computational demanding for most laptops. In such cases, we can either opt for the simpler model - keeping in mind that we are not allowing the estimates to vary in their timing of activity - or we can run this model on a computing cluster.</p>
</div>
<div id="cyclic-cubic-spline-hgams-1" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Cyclic cubic spline HGAMs<a href="cov.html#cyclic-cubic-spline-hgams-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Similar to trigonometric GLMMs, cyclic cubic spline HGAMs can also be used to model activity patterns as a function of a categorical covariate. As we explained in Tutorial <a href="est.html#est">3</a>, this class of models is highly flexible and offers a plethora of options when it comes to choosing a model structure. Here we focus on two model specifications. The first resembles a trigonometric random intercept-only GLMM and contains <code>Season</code> as a fixed term, a cubic cyclic smoother for <code>Time</code> which varies by <code>Season</code>, and a smoother for <code>Site</code> as a random effect. This structure accommodates variability in the frequency of site-use, but not in the timing of activity.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="cov.html#cb88-1" tabindex="-1"></a><span class="co"># &#39;Random intercept-only&#39;</span></span>
<span id="cb88-2"><a href="cov.html#cb88-2" tabindex="-1"></a>mod_cycl1 <span class="ot">&lt;-</span> <span class="fu">bam</span>(<span class="fu">cbind</span>(success, failure) <span class="sc">~</span></span>
<span id="cb88-3"><a href="cov.html#cb88-3" tabindex="-1"></a>                   Season <span class="sc">+</span> </span>
<span id="cb88-4"><a href="cov.html#cb88-4" tabindex="-1"></a>                   <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">&quot;cc&quot;</span>, <span class="at">k =</span> <span class="dv">12</span>, <span class="at">by =</span> Season, <span class="at">m =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb88-5"><a href="cov.html#cb88-5" tabindex="-1"></a>                   <span class="fu">s</span>(Site, <span class="at">bs=</span><span class="st">&quot;re&quot;</span>), </span>
<span id="cb88-6"><a href="cov.html#cb88-6" tabindex="-1"></a>                  <span class="at">knots =</span> <span class="fu">list</span>(<span class="at">Time=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">23</span>)),</span>
<span id="cb88-7"><a href="cov.html#cb88-7" tabindex="-1"></a>                  <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb88-8"><a href="cov.html#cb88-8" tabindex="-1"></a>                  <span class="at">data =</span> occasions_cbind</span>
<span id="cb88-9"><a href="cov.html#cb88-9" tabindex="-1"></a>                 )</span>
<span id="cb88-10"><a href="cov.html#cb88-10" tabindex="-1"></a></span>
<span id="cb88-11"><a href="cov.html#cb88-11" tabindex="-1"></a><span class="co"># Predict activity patterns</span></span>
<span id="cb88-12"><a href="cov.html#cb88-12" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">with</span>(occasions_cbind, </span>
<span id="cb88-13"><a href="cov.html#cb88-13" tabindex="-1"></a>               <span class="fu">expand.grid</span>(<span class="at">Time =</span> <span class="fu">seq</span>(<span class="fu">min</span>(Time), <span class="fu">max</span>(Time), <span class="dv">1</span>), </span>
<span id="cb88-14"><a href="cov.html#cb88-14" tabindex="-1"></a>                           <span class="at">Season =</span> <span class="fu">levels</span>(Season), </span>
<span id="cb88-15"><a href="cov.html#cb88-15" tabindex="-1"></a>                           <span class="at">Site =</span> <span class="st">&quot;7B&quot;</span> <span class="co">#Station doesn&#39;t matter</span></span>
<span id="cb88-16"><a href="cov.html#cb88-16" tabindex="-1"></a>                           ) </span>
<span id="cb88-17"><a href="cov.html#cb88-17" tabindex="-1"></a>               ) </span>
<span id="cb88-18"><a href="cov.html#cb88-18" tabindex="-1"></a></span>
<span id="cb88-19"><a href="cov.html#cb88-19" tabindex="-1"></a></span>
<span id="cb88-20"><a href="cov.html#cb88-20" tabindex="-1"></a>cycl_pred1 <span class="ot">&lt;-</span> <span class="fu">predict.bam</span>(mod_cycl1, </span>
<span id="cb88-21"><a href="cov.html#cb88-21" tabindex="-1"></a>                          <span class="at">newdata =</span> newdat,  </span>
<span id="cb88-22"><a href="cov.html#cb88-22" tabindex="-1"></a>                          <span class="at">exclude =</span> <span class="st">&quot;s(Site)&quot;</span>, </span>
<span id="cb88-23"><a href="cov.html#cb88-23" tabindex="-1"></a>                          <span class="at">se.fit =</span> <span class="cn">TRUE</span>, </span>
<span id="cb88-24"><a href="cov.html#cb88-24" tabindex="-1"></a>                          <span class="at">type =</span> <span class="st">&quot;response&quot;</span></span>
<span id="cb88-25"><a href="cov.html#cb88-25" tabindex="-1"></a>                          ) </span>
<span id="cb88-26"><a href="cov.html#cb88-26" tabindex="-1"></a>cycl_pred1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdat, </span>
<span id="cb88-27"><a href="cov.html#cb88-27" tabindex="-1"></a>                    <span class="at">fit=</span>cycl_pred1<span class="sc">$</span>fit, </span>
<span id="cb88-28"><a href="cov.html#cb88-28" tabindex="-1"></a>                    <span class="at">se.fit=</span>cycl_pred1<span class="sc">$</span>se.fit, </span>
<span id="cb88-29"><a href="cov.html#cb88-29" tabindex="-1"></a>                    <span class="at">Model =</span> <span class="st">&quot;Random intercept-only&quot;</span></span>
<span id="cb88-30"><a href="cov.html#cb88-30" tabindex="-1"></a>                    )</span></code></pre></div>
<div class="sourceCode" id="cb89"><pre class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb89-1"><a href="cov.html#cb89-1" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb89-2"><a href="cov.html#cb89-2" tabindex="-1"></a>pl_cycl1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cycl_pred1, <span class="fu">aes</span>(Time, fit)) <span class="sc">+</span></span>
<span id="cb89-3"><a href="cov.html#cb89-3" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> fit<span class="fl">-1.96</span><span class="sc">*</span>se.fit, <span class="at">ymax =</span> fit<span class="fl">+1.96</span><span class="sc">*</span>se.fit, <span class="at">color =</span> Season, <span class="at">fill =</span> Season), <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb89-4"><a href="cov.html#cb89-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> Season), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb89-5"><a href="cov.html#cb89-5" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;orange&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)) <span class="sc">+</span></span>
<span id="cb89-6"><a href="cov.html#cb89-6" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;orange&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)) <span class="sc">+</span></span>
<span id="cb89-7"><a href="cov.html#cb89-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time of Day (Hour)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Predicted Activity Pattern </span><span class="sc">\n</span><span class="st"> (probability)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;B: Hierarchical model, </span><span class="sc">\n</span><span class="st">Cyclic cubic spline HGAM&quot;</span>)<span class="sc">+</span></span>
<span id="cb89-8"><a href="cov.html#cb89-8" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.005</span>)) <span class="sc">+</span></span>
<span id="cb89-9"><a href="cov.html#cb89-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb89-10"><a href="cov.html#cb89-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,</span>
<span id="cb89-11"><a href="cov.html#cb89-11" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb89-12"><a href="cov.html#cb89-12" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb89-13"><a href="cov.html#cb89-13" tabindex="-1"></a>        <span class="at">legend.margin=</span><span class="fu">margin</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb89-14"><a href="cov.html#cb89-14" tabindex="-1"></a>        <span class="at">legend.box.margin=</span><span class="fu">margin</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>),</span>
<span id="cb89-15"><a href="cov.html#cb89-15" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb89-16"><a href="cov.html#cb89-16" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb89-17"><a href="cov.html#cb89-17" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb89-18"><a href="cov.html#cb89-18" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">9</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb89-19"><a href="cov.html#cb89-19" tabindex="-1"></a>        <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb89-20"><a href="cov.html#cb89-20" tabindex="-1"></a>        <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb89-21"><a href="cov.html#cb89-21" tabindex="-1"></a>        <span class="at">panel.grid.major.x =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;lightgrey&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;dashed&#39;</span>, <span class="at">linewidth=</span><span class="fl">0.5</span>),</span>
<span id="cb89-22"><a href="cov.html#cb89-22" tabindex="-1"></a>        <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb89-23"><a href="cov.html#cb89-23" tabindex="-1"></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">hjust =</span> <span class="dv">0</span>)</span>
<span id="cb89-24"><a href="cov.html#cb89-24" tabindex="-1"></a>        ) <span class="sc">+</span></span>
<span id="cb89-25"><a href="cov.html#cb89-25" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="fu">max</span>(cycl_pred1<span class="sc">$</span>Time),<span class="at">length.out=</span><span class="dv">7</span>), <span class="at">labels=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">24</span>,<span class="dv">4</span>)) </span>
<span id="cb89-26"><a href="cov.html#cb89-26" tabindex="-1"></a></span>
<span id="cb89-27"><a href="cov.html#cb89-27" tabindex="-1"></a><span class="co"># bringing hierarchical models plot together</span></span>
<span id="cb89-28"><a href="cov.html#cb89-28" tabindex="-1"></a>(<span class="fu">ggarrange</span>(pl_trig, pl_cycl1, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">common.legend =</span> <span class="cn">TRUE</span>, <span class="at">legend =</span> <span class="st">&quot;bottom&quot;</span>, <span class="at">widths =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb89-29"><a href="cov.html#cb89-29" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="fl">0.1</span>,<span class="fl">0.1</span>,<span class="fl">0.5</span>,<span class="fl">0.1</span>, <span class="st">&quot;cm&quot;</span>)))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cat5b"></span>
<img src="HMsActivity_files/figure-html/cat5b-1.png" alt="Predicted probability of activity of black bears in the spring (S) and fall (F) using a random intercept-only trigonometric hierarchical model (A) and a cyclic cubic spline hierarhical model (B); shading corresponds to 95% confidence intervals." width="672" />
<p class="caption">
Figure 6.2: Predicted probability of activity of black bears in the spring (S) and fall (F) using a random intercept-only trigonometric hierarchical model (A) and a cyclic cubic spline hierarhical model (B); shading corresponds to 95% confidence intervals.
</p>
</div>
<p>The patterns estimated by the cyclic cubic spline model closely matches that returned by the random intercept-only trigonometric model, though the curve is slightly more irregular.</p>
<p><strong>Model selection:</strong> As done for the trigonometric models, we can use AIC to test the importance of the variable <code>Season</code> by comparing models with and without terms involving the covariate of interest.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="cov.html#cb90-1" tabindex="-1"></a><span class="co"># Without general smoother for Time, no covariate effect</span></span>
<span id="cb90-2"><a href="cov.html#cb90-2" tabindex="-1"></a>mod_cycl1_no_cov <span class="ot">&lt;-</span> <span class="fu">bam</span>(<span class="fu">cbind</span>(success, failure) <span class="sc">~</span> </span>
<span id="cb90-3"><a href="cov.html#cb90-3" tabindex="-1"></a>                          <span class="fu">s</span>(Site, <span class="at">bs=</span><span class="st">&quot;re&quot;</span>), </span>
<span id="cb90-4"><a href="cov.html#cb90-4" tabindex="-1"></a>                        <span class="at">knots =</span> <span class="fu">list</span>(<span class="at">Time=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">23</span>)),</span>
<span id="cb90-5"><a href="cov.html#cb90-5" tabindex="-1"></a>                        <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb90-6"><a href="cov.html#cb90-6" tabindex="-1"></a>                        <span class="at">data =</span> occasions_cbind</span>
<span id="cb90-7"><a href="cov.html#cb90-7" tabindex="-1"></a>                        )</span>
<span id="cb90-8"><a href="cov.html#cb90-8" tabindex="-1"></a></span>
<span id="cb90-9"><a href="cov.html#cb90-9" tabindex="-1"></a></span>
<span id="cb90-10"><a href="cov.html#cb90-10" tabindex="-1"></a><span class="fu">AIC</span>(mod_cycl1, mod_cycl1_no_cov)</span></code></pre></div>
<pre><code>##                        df      AIC
## mod_cycl1        98.46857 4441.474
## mod_cycl1_no_cov 83.49616 4936.451</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="cov.html#cb92-1" tabindex="-1"></a><span class="fu">AIC</span>(mod_cycl1_no_cov) <span class="sc">-</span> <span class="fu">AIC</span>(mod_cycl1)</span></code></pre></div>
<pre><code>## [1] 494.977</code></pre>
<p>Importantly, (generalized) LRTs should be viewed with some caution. For example, <span class="citation">Pedersen et al. (<a href="references.html#ref-Pedersen2019">2019</a>)</span> suggest there is insufficient theory to support their use, and <span class="citation">S. N. Wood (<a href="references.html#ref-Wood2017">2017b</a>)</span> note that <em>p-values</em> tend to be too small (usually half of what they should be).
Thus, whenever possible, we recommend careful <em>a priori</em> choice of modeling structures based on the desired inference and the characteristics of the data.</p>
<p>We can extend the previous model structure to accommodate site-to-site variability in timing of activity by adding a smoother for <code>Time</code> that depends on <code>Site</code>. We also add a global smoother for <code>Time</code> that shrinks the site-specific estimates towards a common curve. This structure mimics a trigonometric random intercept and random slope model and allows the site-specific activity curves to vary not only in their intercept but also in their shape.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="cov.html#cb94-1" tabindex="-1"></a><span class="co"># &#39;Random intercept and slope&#39;</span></span>
<span id="cb94-2"><a href="cov.html#cb94-2" tabindex="-1"></a>mod_cycl2 <span class="ot">&lt;-</span> <span class="fu">bam</span>(<span class="fu">cbind</span>(success, failure) <span class="sc">~</span> </span>
<span id="cb94-3"><a href="cov.html#cb94-3" tabindex="-1"></a>                   Season <span class="sc">+</span> </span>
<span id="cb94-4"><a href="cov.html#cb94-4" tabindex="-1"></a>                   <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">&quot;cc&quot;</span>, <span class="at">k =</span> <span class="dv">12</span>) <span class="sc">+</span> <span class="co"># global smoother</span></span>
<span id="cb94-5"><a href="cov.html#cb94-5" tabindex="-1"></a>                   <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">&quot;cc&quot;</span>, <span class="at">k =</span> <span class="dv">12</span>, <span class="at">by =</span> Site, <span class="at">m =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb94-6"><a href="cov.html#cb94-6" tabindex="-1"></a>                   <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">&quot;cc&quot;</span>, <span class="at">k =</span> <span class="dv">12</span>, <span class="at">by =</span> Season, <span class="at">m =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb94-7"><a href="cov.html#cb94-7" tabindex="-1"></a>                   <span class="fu">s</span>(Site, <span class="at">bs=</span><span class="st">&quot;re&quot;</span>), </span>
<span id="cb94-8"><a href="cov.html#cb94-8" tabindex="-1"></a>                 <span class="at">knots =</span> <span class="fu">list</span>(<span class="at">Time=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">23</span>)),</span>
<span id="cb94-9"><a href="cov.html#cb94-9" tabindex="-1"></a>                 <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb94-10"><a href="cov.html#cb94-10" tabindex="-1"></a>                 <span class="at">data =</span> occasions_cbind</span>
<span id="cb94-11"><a href="cov.html#cb94-11" tabindex="-1"></a>                 )</span>
<span id="cb94-12"><a href="cov.html#cb94-12" tabindex="-1"></a><span class="co">#summary(mod_cycl2)</span></span>
<span id="cb94-13"><a href="cov.html#cb94-13" tabindex="-1"></a><span class="fu">AIC</span>(mod_cycl1) <span class="sc">-</span> <span class="fu">AIC</span>(mod_cycl2)</span></code></pre></div>
<pre><code>## [1] 8.390475</code></pre>
<p>This model is more supported than the previous one. Plotting some of the estimated site-specific curves shows how the activity patterns can vary greatly among sites.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="cov.html#cb96-1" tabindex="-1"></a><span class="co"># Predict site-specific activity patterns</span></span>
<span id="cb96-2"><a href="cov.html#cb96-2" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">with</span>(occasions_cbind, </span>
<span id="cb96-3"><a href="cov.html#cb96-3" tabindex="-1"></a>               <span class="fu">expand.grid</span>(<span class="at">Time =</span> <span class="fu">seq</span>(<span class="fu">min</span>(Time), <span class="fu">max</span>(Time), <span class="dv">1</span>), </span>
<span id="cb96-4"><a href="cov.html#cb96-4" tabindex="-1"></a>                           <span class="at">Season =</span> <span class="fu">levels</span>(Season), </span>
<span id="cb96-5"><a href="cov.html#cb96-5" tabindex="-1"></a>                           <span class="at">Site =</span>  <span class="fu">unique</span>(occasions_cbind<span class="sc">$</span>Site)</span>
<span id="cb96-6"><a href="cov.html#cb96-6" tabindex="-1"></a>                           )</span>
<span id="cb96-7"><a href="cov.html#cb96-7" tabindex="-1"></a>               ) </span>
<span id="cb96-8"><a href="cov.html#cb96-8" tabindex="-1"></a></span>
<span id="cb96-9"><a href="cov.html#cb96-9" tabindex="-1"></a></span>
<span id="cb96-10"><a href="cov.html#cb96-10" tabindex="-1"></a>cycl_pred1 <span class="ot">&lt;-</span> <span class="fu">predict.bam</span>(mod_cycl1, </span>
<span id="cb96-11"><a href="cov.html#cb96-11" tabindex="-1"></a>                          <span class="at">newdata =</span> newdat,  </span>
<span id="cb96-12"><a href="cov.html#cb96-12" tabindex="-1"></a>                          <span class="at">exclude =</span> <span class="cn">NULL</span>, </span>
<span id="cb96-13"><a href="cov.html#cb96-13" tabindex="-1"></a>                          <span class="at">se.fit =</span> <span class="cn">TRUE</span>, </span>
<span id="cb96-14"><a href="cov.html#cb96-14" tabindex="-1"></a>                          <span class="at">type =</span> <span class="st">&quot;response&quot;</span></span>
<span id="cb96-15"><a href="cov.html#cb96-15" tabindex="-1"></a>                          ) </span>
<span id="cb96-16"><a href="cov.html#cb96-16" tabindex="-1"></a></span>
<span id="cb96-17"><a href="cov.html#cb96-17" tabindex="-1"></a>cycl_pred1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdat, </span>
<span id="cb96-18"><a href="cov.html#cb96-18" tabindex="-1"></a>                    <span class="at">fit=</span>cycl_pred1<span class="sc">$</span>fit, </span>
<span id="cb96-19"><a href="cov.html#cb96-19" tabindex="-1"></a>                    <span class="at">se.fit=</span>cycl_pred1<span class="sc">$</span>se.fit, </span>
<span id="cb96-20"><a href="cov.html#cb96-20" tabindex="-1"></a>                    <span class="at">Model =</span> <span class="st">&quot;Random intercept-only&quot;</span></span>
<span id="cb96-21"><a href="cov.html#cb96-21" tabindex="-1"></a>                    )</span>
<span id="cb96-22"><a href="cov.html#cb96-22" tabindex="-1"></a></span>
<span id="cb96-23"><a href="cov.html#cb96-23" tabindex="-1"></a>cycl_pred2 <span class="ot">&lt;-</span> <span class="fu">predict.bam</span>(mod_cycl2, </span>
<span id="cb96-24"><a href="cov.html#cb96-24" tabindex="-1"></a>                          <span class="at">newdata =</span> newdat,  </span>
<span id="cb96-25"><a href="cov.html#cb96-25" tabindex="-1"></a>                          <span class="at">exclude =</span> <span class="cn">NULL</span>, </span>
<span id="cb96-26"><a href="cov.html#cb96-26" tabindex="-1"></a>                          <span class="at">se.fit =</span> <span class="cn">TRUE</span>, </span>
<span id="cb96-27"><a href="cov.html#cb96-27" tabindex="-1"></a>                          <span class="at">type =</span> <span class="st">&quot;response&quot;</span></span>
<span id="cb96-28"><a href="cov.html#cb96-28" tabindex="-1"></a>                          ) </span>
<span id="cb96-29"><a href="cov.html#cb96-29" tabindex="-1"></a></span>
<span id="cb96-30"><a href="cov.html#cb96-30" tabindex="-1"></a>cycl_pred2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdat, </span>
<span id="cb96-31"><a href="cov.html#cb96-31" tabindex="-1"></a>                    <span class="at">fit=</span>cycl_pred2<span class="sc">$</span>fit, </span>
<span id="cb96-32"><a href="cov.html#cb96-32" tabindex="-1"></a>                    <span class="at">se.fit=</span>cycl_pred2<span class="sc">$</span>se.fit, </span>
<span id="cb96-33"><a href="cov.html#cb96-33" tabindex="-1"></a>                    <span class="at">Model =</span> <span class="st">&quot;Random intercept and slope&quot;</span></span>
<span id="cb96-34"><a href="cov.html#cb96-34" tabindex="-1"></a>                    )</span>
<span id="cb96-35"><a href="cov.html#cb96-35" tabindex="-1"></a></span>
<span id="cb96-36"><a href="cov.html#cb96-36" tabindex="-1"></a>cycl_pred <span class="ot">&lt;-</span> <span class="fu">rbind</span>(cycl_pred1, cycl_pred2)</span></code></pre></div>
<div class="sourceCode" id="cb97"><pre class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb97-1"><a href="cov.html#cb97-1" tabindex="-1"></a>selected_sites <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2A&quot;</span>, <span class="st">&quot;2B&quot;</span>, <span class="st">&quot;3B&quot;</span>, <span class="st">&quot;4D&quot;</span>,<span class="st">&quot;7B&quot;</span>, <span class="st">&quot;14B&quot;</span>, <span class="st">&quot;14C&quot;</span>, <span class="st">&quot;15A&quot;</span>, <span class="st">&quot;15E&quot;</span>, <span class="st">&quot;18C&quot;</span>)</span>
<span id="cb97-2"><a href="cov.html#cb97-2" tabindex="-1"></a>pl_cycl <span class="ot">&lt;-</span> cycl_pred <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Site <span class="sc">%in%</span> selected_sites) <span class="sc">%&gt;%</span> </span>
<span id="cb97-3"><a href="cov.html#cb97-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Season2 =</span> <span class="fu">ifelse</span>(Season <span class="sc">==</span> <span class="st">&quot;F&quot;</span>, <span class="st">&quot;Fall&quot;</span>, <span class="st">&quot;Spring&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb97-4"><a href="cov.html#cb97-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(., <span class="fu">aes</span>(Time, fit, <span class="at">group =</span> Site)) <span class="sc">+</span></span>
<span id="cb97-5"><a href="cov.html#cb97-5" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> Site, <span class="at">group =</span> Site), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb97-6"><a href="cov.html#cb97-6" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time of Day (Hour)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Predicted Activity Pattern </span><span class="sc">\n</span><span class="st"> (probability)&quot;</span>, <span class="at">title =</span> <span class="st">&quot;Cyclic cubic spline HGAMs&quot;</span>)<span class="sc">+</span></span>
<span id="cb97-7"><a href="cov.html#cb97-7" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb97-8"><a href="cov.html#cb97-8" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,</span>
<span id="cb97-9"><a href="cov.html#cb97-9" tabindex="-1"></a>          <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb97-10"><a href="cov.html#cb97-10" tabindex="-1"></a>          <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb97-11"><a href="cov.html#cb97-11" tabindex="-1"></a>          <span class="at">legend.margin=</span><span class="fu">margin</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb97-12"><a href="cov.html#cb97-12" tabindex="-1"></a>          <span class="at">legend.box.margin=</span><span class="fu">margin</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>),</span>
<span id="cb97-13"><a href="cov.html#cb97-13" tabindex="-1"></a>          <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb97-14"><a href="cov.html#cb97-14" tabindex="-1"></a>          <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb97-15"><a href="cov.html#cb97-15" tabindex="-1"></a>          <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb97-16"><a href="cov.html#cb97-16" tabindex="-1"></a>          <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">9</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb97-17"><a href="cov.html#cb97-17" tabindex="-1"></a>          <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb97-18"><a href="cov.html#cb97-18" tabindex="-1"></a>          <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb97-19"><a href="cov.html#cb97-19" tabindex="-1"></a>          <span class="at">panel.grid.major.x =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;lightgrey&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;dashed&#39;</span>, <span class="at">linewidth=</span><span class="fl">0.5</span>),</span>
<span id="cb97-20"><a href="cov.html#cb97-20" tabindex="-1"></a>          <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb97-21"><a href="cov.html#cb97-21" tabindex="-1"></a>          <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb97-22"><a href="cov.html#cb97-22" tabindex="-1"></a>          <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="fl">0.1</span>,<span class="fl">0.1</span>,<span class="fl">0.5</span>,<span class="fl">0.1</span>, <span class="st">&quot;cm&quot;</span>)</span>
<span id="cb97-23"><a href="cov.html#cb97-23" tabindex="-1"></a>          ) <span class="sc">+</span></span>
<span id="cb97-24"><a href="cov.html#cb97-24" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="fu">max</span>(cycl_pred<span class="sc">$</span>Time),<span class="at">length.out=</span><span class="dv">7</span>), <span class="at">labels=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">24</span>,<span class="dv">4</span>)) <span class="sc">+</span></span>
<span id="cb97-25"><a href="cov.html#cb97-25" tabindex="-1"></a>    <span class="fu">facet_grid</span>(Season2<span class="sc">~</span>Model)  </span>
<span id="cb97-26"><a href="cov.html#cb97-26" tabindex="-1"></a></span>
<span id="cb97-27"><a href="cov.html#cb97-27" tabindex="-1"></a>pl_cycl</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cat8b"></span>
<img src="HMsActivity_files/figure-html/cat8b-1.png" alt="Predicted probability of activity of black bears across a select group of sites using a cyclic cubic spline model with a structured resembling a trigonometric random intercept-only (left column) and random intercept and slope (right column) model." width="672" />
<p class="caption">
Figure 6.3: Predicted probability of activity of black bears across a select group of sites using a cyclic cubic spline model with a structured resembling a trigonometric random intercept-only (left column) and random intercept and slope (right column) model.
</p>
</div>
<div class="sourceCode" id="cb98"><pre class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb98-1"><a href="cov.html#cb98-1" tabindex="-1"></a><span class="co"># save plot</span></span>
<span id="cb98-2"><a href="cov.html#cb98-2" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">plot =</span> pl_cycl, <span class="at">filename =</span> <span class="st">&quot;ms_figures/Fig4_Site_specific_estimates.jpg&quot;</span>, <span class="at">device =</span> <span class="st">&quot;jpeg&quot;</span>, <span class="at">units =</span> <span class="st">&quot;cm&quot;</span>, <span class="at">width =</span> <span class="dv">24</span>, <span class="at">height =</span> <span class="dv">20</span>, <span class="at">dpi =</span> <span class="dv">600</span>)</span></code></pre></div>
</div>
</div>
<div id="cont" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Continuous covariates<a href="cov.html#cont" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We use the same data to illustrate how hierarchical models can be used to quantify effects of continuous covariates. Specifically, we explore how bear diel activity changes in response to anthropogenic modifications of the landscape quantified through the Global Human Modification index (GHM; <span class="citation">Kennedy and Kiesecker (<a href="references.html#ref-Kennedyea2020">2020</a>)</span>; <span class="citation">Kennedy and Kiesecker (<a href="references.html#ref-Kennedyea2019">2019</a>)</span>), a continuous measure of human modification of terrestrial landscapes that ranges between 0 and 1. A histogram of the values of GHM at the different sites indicates that the level of human-driven landscape modification is relatively low in the study area with most sites having a GHM value lower than 0.10.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="cov.html#cb99-1" tabindex="-1"></a><span class="fu">hist</span>(cov<span class="sc">$</span>ghm)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cont1"></span>
<img src="HMsActivity_files/figure-html/cont1-1.png" alt="Frequency of observed global human modification index (GHM) values across camera sites." width="672" />
<p class="caption">
Figure 6.4: Frequency of observed global human modification index (GHM) values across camera sites.
</p>
</div>
<p>We link the GHM values available in the <em>cov</em> object to the <em>occasion</em> dataframe created at the beginning of this tutorial, and then proceed with arranging the data in the format required to run the hierarchical model as we have done in other examples. This time though, we also add GHM as an additional grouping level.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="cov.html#cb100-1" tabindex="-1"></a><span class="co"># Add ghm info</span></span>
<span id="cb100-2"><a href="cov.html#cb100-2" tabindex="-1"></a>occasions <span class="ot">&lt;-</span> <span class="fu">left_join</span>(occasions, </span>
<span id="cb100-3"><a href="cov.html#cb100-3" tabindex="-1"></a>                       cov <span class="sc">%&gt;%</span> <span class="fu">select</span>(Session, Site, ghm)) <span class="sc">%&gt;%</span> </span>
<span id="cb100-4"><a href="cov.html#cb100-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ghm =</span> <span class="fu">round</span>(ghm, <span class="at">digits =</span> <span class="dv">3</span>))</span></code></pre></div>
<pre><code>## Joining with `by = join_by(Session, Site)`</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="cov.html#cb102-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">table</span>(occasions<span class="sc">$</span>ghm, occasions<span class="sc">$</span>capt))</span></code></pre></div>
<pre><code>##        
##             0     1
##   0.015  9397    35
##   0.017 15332    28
##   0.018  7849    47
##   0.02   5972     4
##   0.021  4264     8
##   0.022 13961    31</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="cov.html#cb104-1" tabindex="-1"></a>occasions<span class="sc">$</span>Site <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(occasions<span class="sc">$</span>Site)</span>
<span id="cb104-2"><a href="cov.html#cb104-2" tabindex="-1"></a></span>
<span id="cb104-3"><a href="cov.html#cb104-3" tabindex="-1"></a><span class="co"># format data for cbind(success, failure)</span></span>
<span id="cb104-4"><a href="cov.html#cb104-4" tabindex="-1"></a>occasions_cbind <span class="ot">&lt;-</span> occasions <span class="sc">%&gt;%</span> </span>
<span id="cb104-5"><a href="cov.html#cb104-5" tabindex="-1"></a>  <span class="fu">group_by</span>(Site, Time, ghm) <span class="sc">%&gt;%</span> </span>
<span id="cb104-6"><a href="cov.html#cb104-6" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">success =</span> <span class="fu">sum</span>(capt),</span>
<span id="cb104-7"><a href="cov.html#cb104-7" tabindex="-1"></a>            <span class="at">failure =</span> <span class="fu">n</span>() <span class="sc">-</span> success)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Site&#39;, &#39;Time&#39;. You can override using the `.groups` argument.</code></pre>
<p>We can now apply either trigonometric GLMMs or HGAMs to the data. As an example, we report a trigonometric random intercept-only model and a cyclic cubic spline HGAM without a site-specific smoother.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="cov.html#cb106-1" tabindex="-1"></a><span class="co"># random intercept-only trigonometric GLMM</span></span>
<span id="cb106-2"><a href="cov.html#cb106-2" tabindex="-1"></a>mod_trig_cont <span class="ot">&lt;-</span> <span class="fu">mixed_model</span>(<span class="at">fixed =</span> <span class="fu">cbind</span>(success, failure) <span class="sc">~</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> ghm <span class="sc">+</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">*</span> ghm <span class="sc">+</span></span>
<span id="cb106-3"><a href="cov.html#cb106-3" tabindex="-1"></a>                                                               <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> ghm <span class="sc">+</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">*</span> ghm,</span>
<span id="cb106-4"><a href="cov.html#cb106-4" tabindex="-1"></a>                             <span class="at">random =</span> <span class="sc">~</span>  <span class="dv">1</span>  <span class="sc">|</span>   Site,</span>
<span id="cb106-5"><a href="cov.html#cb106-5" tabindex="-1"></a>                             <span class="at">data =</span> occasions_cbind, </span>
<span id="cb106-6"><a href="cov.html#cb106-6" tabindex="-1"></a>                             <span class="at">family =</span> <span class="fu">binomial</span>(), </span>
<span id="cb106-7"><a href="cov.html#cb106-7" tabindex="-1"></a>                             <span class="at">iter_EM =</span> <span class="dv">0</span></span>
<span id="cb106-8"><a href="cov.html#cb106-8" tabindex="-1"></a>                             )</span>
<span id="cb106-9"><a href="cov.html#cb106-9" tabindex="-1"></a><span class="fu">summary</span>(mod_trig_cont)</span></code></pre></div>
<pre><code>## 
## Call:
## mixed_model(fixed = cbind(success, failure) ~ cos(2 * pi * Time/24) * 
##     ghm + sin(2 * pi * Time/24) * ghm + sin(2 * pi * Time/12) * 
##     ghm + cos(2 * pi * Time/12) * ghm, random = ~1 | Site, data = occasions_cbind, 
##     family = binomial(), iter_EM = 0)
## 
## Data Descriptives:
## Number of Observations: 2784
## Number of Groups: 100 
## 
## Model:
##  family: binomial
##  link: logit 
## 
## Fit statistics:
##    log.Lik      AIC      BIC
##  -1907.898 3837.795 3866.452
## 
## Random effects covariance matrix:
##                StdDev
## (Intercept) 0.8716829
## 
## Fixed effects:
##                           Estimate Std.Err  z-value p-value
## (Intercept)                -6.5825  0.1437 -45.8218 &lt; 1e-04
## cos(2 * pi * Time/24)      -0.0752  0.0789  -0.9535 0.34036
## ghm                        -2.8516  1.5657  -1.8214 0.06855
## sin(2 * pi * Time/24)      -0.3062  0.0625  -4.8980 &lt; 1e-04
## sin(2 * pi * Time/12)      -0.4642  0.0710  -6.5403 &lt; 1e-04
## cos(2 * pi * Time/12)      -0.4561  0.0705  -6.4672 &lt; 1e-04
## cos(2 * pi * Time/24):ghm   0.1742  0.9703   0.1796 0.85750
## ghm:sin(2 * pi * Time/24)   0.8375  0.7415   1.1294 0.25872
## ghm:sin(2 * pi * Time/12)  -0.9825  0.8686  -1.1311 0.25802
## ghm:cos(2 * pi * Time/12)  -0.6938  0.8599  -0.8068 0.41979
## 
## Integration:
## method: adaptive Gauss-Hermite quadrature rule
## quadrature points: 11
## 
## Optimization:
## method: quasi-Newton
## converged: TRUE</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="cov.html#cb108-1" tabindex="-1"></a><span class="co"># cyclic cubic spline HGAM without common smoother for Time</span></span>
<span id="cb108-2"><a href="cov.html#cb108-2" tabindex="-1"></a>mod_cycl1_cont <span class="ot">&lt;-</span> <span class="fu">bam</span>(<span class="fu">cbind</span>(success, failure) <span class="sc">~</span> ghm <span class="sc">+</span> </span>
<span id="cb108-3"><a href="cov.html#cb108-3" tabindex="-1"></a>                        <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">&quot;cc&quot;</span>, <span class="at">k =</span> <span class="dv">12</span>, <span class="at">by =</span> ghm, <span class="at">m =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb108-4"><a href="cov.html#cb108-4" tabindex="-1"></a>                        <span class="fu">s</span>(Site, <span class="at">bs=</span><span class="st">&quot;re&quot;</span>), </span>
<span id="cb108-5"><a href="cov.html#cb108-5" tabindex="-1"></a>                      <span class="at">knots =</span> <span class="fu">list</span>(<span class="at">Time=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">23</span>)),</span>
<span id="cb108-6"><a href="cov.html#cb108-6" tabindex="-1"></a>                      <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb108-7"><a href="cov.html#cb108-7" tabindex="-1"></a>                      <span class="at">data =</span> occasions_cbind</span>
<span id="cb108-8"><a href="cov.html#cb108-8" tabindex="-1"></a>                      )</span>
<span id="cb108-9"><a href="cov.html#cb108-9" tabindex="-1"></a><span class="fu">summary</span>(mod_cycl1_cont)</span></code></pre></div>
<pre><code>## 
## Family: binomial 
## Link function: logit 
## 
## Formula:
## cbind(success, failure) ~ ghm + s(Time, bs = &quot;cc&quot;, k = 12, by = ghm, 
##     m = 1) + s(Site, bs = &quot;re&quot;)
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -6.2804     0.1353 -46.427  &lt; 2e-16 ***
## ghm          -5.8321     1.5420  -3.782 0.000155 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##                edf Ref.df Chi.sq p-value    
## s(Time):ghm  7.908  9.079  143.1  &lt;2e-16 ***
## s(Site)     80.847 99.000  603.9  &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Rank: 112/113
## R-sq.(adj) =  0.243   Deviance explained = 30.7%
## fREML = 4135.1  Scale est. = 1         n = 2784</code></pre>
<p>To facilitate understanding, we compare the model-based estimates of activity visually for different quantiles (0.025, 0.5 and 0.975) of the GHM covariate.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="cov.html#cb110-1" tabindex="-1"></a><span class="co"># create a new dataset for the estimates</span></span>
<span id="cb110-2"><a href="cov.html#cb110-2" tabindex="-1"></a>newdat <span class="ot">&lt;-</span> <span class="fu">with</span>(occasions_cbind, </span>
<span id="cb110-3"><a href="cov.html#cb110-3" tabindex="-1"></a>               <span class="fu">expand.grid</span>(<span class="at">Time =</span> <span class="fu">seq</span>(<span class="fu">min</span>(Time), <span class="dv">24</span>, <span class="at">length.out =</span> <span class="dv">48</span>),</span>
<span id="cb110-4"><a href="cov.html#cb110-4" tabindex="-1"></a>                           <span class="at">ghm =</span> <span class="fu">quantile</span>(ghm, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)),</span>
<span id="cb110-5"><a href="cov.html#cb110-5" tabindex="-1"></a>                           <span class="at">Site =</span> <span class="st">&quot;7B&quot;</span> <span class="co"># Site does not matter</span></span>
<span id="cb110-6"><a href="cov.html#cb110-6" tabindex="-1"></a>                           )</span>
<span id="cb110-7"><a href="cov.html#cb110-7" tabindex="-1"></a>               ) <span class="sc">%&gt;%</span> </span>
<span id="cb110-8"><a href="cov.html#cb110-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ghm_ft =</span> <span class="fu">as.factor</span>(ghm),</span>
<span id="cb110-9"><a href="cov.html#cb110-9" tabindex="-1"></a>         <span class="at">ghm_ft =</span> <span class="fu">fct_recode</span>(ghm_ft, </span>
<span id="cb110-10"><a href="cov.html#cb110-10" tabindex="-1"></a>                              <span class="st">&quot;Low GHM&quot;</span> <span class="ot">=</span> <span class="fu">levels</span>(ghm_ft)[<span class="dv">1</span>], </span>
<span id="cb110-11"><a href="cov.html#cb110-11" tabindex="-1"></a>                              <span class="st">&quot;Intermediate GHM&quot;</span> <span class="ot">=</span> <span class="fu">levels</span>(ghm_ft)[<span class="dv">2</span>], </span>
<span id="cb110-12"><a href="cov.html#cb110-12" tabindex="-1"></a>                              <span class="st">&quot;High GHM&quot;</span> <span class="ot">=</span> <span class="fu">levels</span>(ghm_ft)[<span class="dv">3</span>])</span>
<span id="cb110-13"><a href="cov.html#cb110-13" tabindex="-1"></a>         )</span>
<span id="cb110-14"><a href="cov.html#cb110-14" tabindex="-1"></a></span>
<span id="cb110-15"><a href="cov.html#cb110-15" tabindex="-1"></a><span class="co"># trigonometric estimates</span></span>
<span id="cb110-16"><a href="cov.html#cb110-16" tabindex="-1"></a>cond_eff_cont <span class="ot">&lt;-</span> <span class="fu">effectPlotData</span>(mod_trig_cont, newdat, <span class="at">marginal =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb110-17"><a href="cov.html#cb110-17" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">plogis</span>(pred),</span>
<span id="cb110-18"><a href="cov.html#cb110-18" tabindex="-1"></a>         <span class="at">low =</span> <span class="fu">plogis</span>(low),</span>
<span id="cb110-19"><a href="cov.html#cb110-19" tabindex="-1"></a>         <span class="at">upp =</span> <span class="fu">plogis</span>(upp),</span>
<span id="cb110-20"><a href="cov.html#cb110-20" tabindex="-1"></a>         <span class="at">Model =</span> <span class="st">&quot;Trig GLMM&quot;</span></span>
<span id="cb110-21"><a href="cov.html#cb110-21" tabindex="-1"></a>         )</span>
<span id="cb110-22"><a href="cov.html#cb110-22" tabindex="-1"></a></span>
<span id="cb110-23"><a href="cov.html#cb110-23" tabindex="-1"></a><span class="co"># cyclic cubic spline estimates</span></span>
<span id="cb110-24"><a href="cov.html#cb110-24" tabindex="-1"></a>cycl_pred1_cont <span class="ot">&lt;-</span> <span class="fu">predict.bam</span>(mod_cycl1_cont, </span>
<span id="cb110-25"><a href="cov.html#cb110-25" tabindex="-1"></a>                               <span class="at">newdata =</span> newdat,  </span>
<span id="cb110-26"><a href="cov.html#cb110-26" tabindex="-1"></a>                               <span class="at">exclude =</span> <span class="st">&quot;s(Site)&quot;</span>, </span>
<span id="cb110-27"><a href="cov.html#cb110-27" tabindex="-1"></a>                               <span class="at">se.fit =</span> <span class="cn">TRUE</span>, </span>
<span id="cb110-28"><a href="cov.html#cb110-28" tabindex="-1"></a>                               <span class="at">type =</span> <span class="st">&quot;response&quot;</span></span>
<span id="cb110-29"><a href="cov.html#cb110-29" tabindex="-1"></a>                               ) </span>
<span id="cb110-30"><a href="cov.html#cb110-30" tabindex="-1"></a></span>
<span id="cb110-31"><a href="cov.html#cb110-31" tabindex="-1"></a>cycl_pred1_cont <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newdat, </span>
<span id="cb110-32"><a href="cov.html#cb110-32" tabindex="-1"></a>                         <span class="at">pred =</span> cycl_pred1_cont<span class="sc">$</span>fit, </span>
<span id="cb110-33"><a href="cov.html#cb110-33" tabindex="-1"></a>                         <span class="at">low =</span> cycl_pred1_cont<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.95</span><span class="sc">*</span>cycl_pred1_cont<span class="sc">$</span>se.fit, </span>
<span id="cb110-34"><a href="cov.html#cb110-34" tabindex="-1"></a>                         <span class="at">upp =</span> cycl_pred1_cont<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.95</span><span class="sc">*</span>cycl_pred1_cont<span class="sc">$</span>se.fit, </span>
<span id="cb110-35"><a href="cov.html#cb110-35" tabindex="-1"></a>                         <span class="at">Model =</span> <span class="st">&quot;CC spline HGAM&quot;</span></span>
<span id="cb110-36"><a href="cov.html#cb110-36" tabindex="-1"></a>                         )</span>
<span id="cb110-37"><a href="cov.html#cb110-37" tabindex="-1"></a></span>
<span id="cb110-38"><a href="cov.html#cb110-38" tabindex="-1"></a><span class="co"># bring together the estimates based on the two approaches</span></span>
<span id="cb110-39"><a href="cov.html#cb110-39" tabindex="-1"></a>pred_cont <span class="ot">&lt;-</span> <span class="fu">rbind</span>(cond_eff_cont, cycl_pred1_cont)</span></code></pre></div>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="cov.html#cb111-1" tabindex="-1"></a><span class="co"># plot results</span></span>
<span id="cb111-2"><a href="cov.html#cb111-2" tabindex="-1"></a><span class="fu">ggplot</span>(pred_cont, <span class="fu">aes</span>(Time, pred)) <span class="sc">+</span></span>
<span id="cb111-3"><a href="cov.html#cb111-3" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> low, <span class="at">ymax =</span> upp, <span class="at">color =</span> ghm_ft, <span class="at">fill =</span> ghm_ft), <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb111-4"><a href="cov.html#cb111-4" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> ghm_ft), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb111-5"><a href="cov.html#cb111-5" tabindex="-1"></a>    <span class="fu">scale_color_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb111-6"><a href="cov.html#cb111-6" tabindex="-1"></a>    <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb111-7"><a href="cov.html#cb111-7" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Time of Day (Hour)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Predicted Activity Pattern </span><span class="sc">\n</span><span class="st"> (probability)&quot;</span>)<span class="sc">+</span></span>
<span id="cb111-8"><a href="cov.html#cb111-8" tabindex="-1"></a>    <span class="co">#coord_cartesian(ylim = c(0, 0.005)) +</span></span>
<span id="cb111-9"><a href="cov.html#cb111-9" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb111-10"><a href="cov.html#cb111-10" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb111-11"><a href="cov.html#cb111-11" tabindex="-1"></a>          <span class="at">legend.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb111-12"><a href="cov.html#cb111-12" tabindex="-1"></a>          <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb111-13"><a href="cov.html#cb111-13" tabindex="-1"></a>          <span class="at">legend.margin=</span><span class="fu">margin</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>),</span>
<span id="cb111-14"><a href="cov.html#cb111-14" tabindex="-1"></a>          <span class="at">legend.box.margin=</span><span class="fu">margin</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>,<span class="sc">-</span><span class="dv">10</span>),</span>
<span id="cb111-15"><a href="cov.html#cb111-15" tabindex="-1"></a>          <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb111-16"><a href="cov.html#cb111-16" tabindex="-1"></a>          <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb111-17"><a href="cov.html#cb111-17" tabindex="-1"></a>          <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;black&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;solid&#39;</span>),</span>
<span id="cb111-18"><a href="cov.html#cb111-18" tabindex="-1"></a>          <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">9</span>,<span class="at">face=</span><span class="st">&quot;bold&quot;</span>),</span>
<span id="cb111-19"><a href="cov.html#cb111-19" tabindex="-1"></a>          <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb111-20"><a href="cov.html#cb111-20" tabindex="-1"></a>          <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb111-21"><a href="cov.html#cb111-21" tabindex="-1"></a>          <span class="at">panel.grid.major.x =</span> <span class="fu">element_line</span>(<span class="at">colour =</span> <span class="st">&#39;lightgrey&#39;</span>, <span class="at">linetype =</span> <span class="st">&#39;dashed&#39;</span>, <span class="at">linewidth=</span><span class="fl">0.5</span>),</span>
<span id="cb111-22"><a href="cov.html#cb111-22" tabindex="-1"></a>          <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb111-23"><a href="cov.html#cb111-23" tabindex="-1"></a>          <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">hjust =</span> <span class="dv">0</span>)</span>
<span id="cb111-24"><a href="cov.html#cb111-24" tabindex="-1"></a>          ) <span class="sc">+</span></span>
<span id="cb111-25"><a href="cov.html#cb111-25" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">23</span>,<span class="at">length.out=</span><span class="dv">7</span>), <span class="at">labels=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">24</span>,<span class="dv">4</span>)) <span class="sc">+</span></span>
<span id="cb111-26"><a href="cov.html#cb111-26" tabindex="-1"></a>    <span class="fu">facet_grid</span>(Model<span class="sc">~</span>ghm_ft)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cont4b"></span>
<img src="HMsActivity_files/figure-html/cont4b-1.png" alt="Predicted probability of activity by black bears varying by levels of the continuous covariate global human modification index (GHM) using a cyclic cubic spline hierarhical model (first row) and trigonometric hierarhical model (second row)." width="672" />
<p class="caption">
Figure 6.5: Predicted probability of activity by black bears varying by levels of the continuous covariate global human modification index (GHM) using a cyclic cubic spline hierarhical model (first row) and trigonometric hierarhical model (second row).
</p>
</div>
<p>The estimates based on the cyclic cubic spline HGAM show a clear progression in the shape of black bears’ activity pattern, from having an almost cathemeral pattern at low level of GHM to a well-defined bimodal pattern at the high level of GHM. This trend is less evident in the estimates based on trigonometric GLMM.</p>
<p>We can further evaluate evidence for the effect of GHM on activity by comparing these models with their relative null model (i.e. a version of the model without the covariate of interest) using AIC (or LRT for trigonometric GLMMs).</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="cov.html#cb112-1" tabindex="-1"></a><span class="co"># null random intercept-only trigonometric GLMM</span></span>
<span id="cb112-2"><a href="cov.html#cb112-2" tabindex="-1"></a>mod_trig_cont_null <span class="ot">&lt;-</span> <span class="fu">mixed_model</span>(<span class="at">fixed =</span> <span class="fu">cbind</span>(success, failure) <span class="sc">~</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">+</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">24</span>) <span class="sc">+</span></span>
<span id="cb112-3"><a href="cov.html#cb112-3" tabindex="-1"></a>                                                                    <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>) <span class="sc">+</span> <span class="fu">cos</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> Time<span class="sc">/</span><span class="dv">12</span>),</span>
<span id="cb112-4"><a href="cov.html#cb112-4" tabindex="-1"></a>                                  <span class="at">random =</span> <span class="sc">~</span>  <span class="dv">1</span>  <span class="sc">|</span>   Site,</span>
<span id="cb112-5"><a href="cov.html#cb112-5" tabindex="-1"></a>                                  <span class="at">data =</span> occasions_cbind, </span>
<span id="cb112-6"><a href="cov.html#cb112-6" tabindex="-1"></a>                                  <span class="at">family =</span> <span class="fu">binomial</span>(), </span>
<span id="cb112-7"><a href="cov.html#cb112-7" tabindex="-1"></a>                                  <span class="at">iter_EM =</span> <span class="dv">0</span></span>
<span id="cb112-8"><a href="cov.html#cb112-8" tabindex="-1"></a>                                  )</span>
<span id="cb112-9"><a href="cov.html#cb112-9" tabindex="-1"></a></span>
<span id="cb112-10"><a href="cov.html#cb112-10" tabindex="-1"></a></span>
<span id="cb112-11"><a href="cov.html#cb112-11" tabindex="-1"></a><span class="co"># null cyclic cubic spline HGAM without common smoother for Time</span></span>
<span id="cb112-12"><a href="cov.html#cb112-12" tabindex="-1"></a>mod_cycl1_cont_null <span class="ot">&lt;-</span> <span class="fu">bam</span>(<span class="fu">cbind</span>(success, failure) <span class="sc">~</span> </span>
<span id="cb112-13"><a href="cov.html#cb112-13" tabindex="-1"></a>                             <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">&quot;cc&quot;</span>, <span class="at">k =</span> <span class="dv">12</span>, <span class="at">m =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb112-14"><a href="cov.html#cb112-14" tabindex="-1"></a>                             <span class="fu">s</span>(Site, <span class="at">bs=</span><span class="st">&quot;re&quot;</span>), </span>
<span id="cb112-15"><a href="cov.html#cb112-15" tabindex="-1"></a>                            <span class="at">knots =</span> <span class="fu">list</span>(<span class="at">Time=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">23</span>)),</span>
<span id="cb112-16"><a href="cov.html#cb112-16" tabindex="-1"></a>                            <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>, </span>
<span id="cb112-17"><a href="cov.html#cb112-17" tabindex="-1"></a>                            <span class="at">data =</span> occasions_cbind</span>
<span id="cb112-18"><a href="cov.html#cb112-18" tabindex="-1"></a>                           )</span>
<span id="cb112-19"><a href="cov.html#cb112-19" tabindex="-1"></a></span>
<span id="cb112-20"><a href="cov.html#cb112-20" tabindex="-1"></a><span class="co"># Comparing trig GLMMs</span></span>
<span id="cb112-21"><a href="cov.html#cb112-21" tabindex="-1"></a><span class="fu">AIC</span>(mod_trig_cont, mod_trig_cont_null)</span></code></pre></div>
<pre><code>##                    df      AIC
## mod_trig_cont      11 3837.795
## mod_trig_cont_null  6 3833.623</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="cov.html#cb114-1" tabindex="-1"></a><span class="fu">AIC</span>(mod_trig_cont_null) <span class="sc">-</span> <span class="fu">AIC</span>(mod_trig_cont)</span></code></pre></div>
<pre><code>## [1] -4.17234</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="cov.html#cb116-1" tabindex="-1"></a><span class="co"># Comparing cyclic cubic spline HGAMs</span></span>
<span id="cb116-2"><a href="cov.html#cb116-2" tabindex="-1"></a><span class="fu">AIC</span>(mod_cycl1_cont, mod_cycl1_cont_null)</span></code></pre></div>
<pre><code>##                           df      AIC
## mod_cycl1_cont      91.44899 3825.111
## mod_cycl1_cont_null 91.92963 3709.086</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="cov.html#cb118-1" tabindex="-1"></a><span class="fu">AIC</span>(mod_cycl1_cont_null) <span class="sc">-</span> <span class="fu">AIC</span>(mod_cycl1_cont)</span></code></pre></div>
<pre><code>## [1] -116.0255</code></pre>
<p>We find that there is little support for an effect of GHM on the activity patterns of American black bear, which is perhaps not surprising given the low level of human disturbance at these sites.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="unibim.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="temppart.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
